---
apiVersion: v1
kind: Service
metadata:
  name: avlav-test-flask-service
  labels:
    username: avlav
    env: test
spec:
  type: ClusterIP
  selector:
    app: avlav-test-flask
  ports:
  - name: avlav-test-flask
    port: 5000
    targetPort: 5000
