---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: avlav-test-redis-pvc
  labels:
    username: avlav
    env: test
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: cinder-csi
  resources:
    requests:
      storage: 1Gi
