---
apiVersion: v1
kind: Service
metadata:
  name: avlav-test-redis-service
  labels:
    username: avlav
    env: test
spec:
  type: ClusterIP
  selector:
    app: avlav-test-redis
  ports:
  - name: avlav-test-redis
    port: 6379
    targetPort: 6379
